development:
  :delivery_method: test
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: saschupestalozzi@gmail.com
  :password: playitagain
  :enable_starttls_auto: true
production:
  :delivery_method: smtp
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: saschupestalozzi@gmail.com
  :password: playitagain
  :enable_starttls_auto: true